# https://taskfile.dev

version: "3" 

tasks:
  install-deps:
    cmds:
      - scoop update
      - scoop install task kubectl busybox starship bottom dust fd fzf jq lsd procs ripgrep gsudo zoxide ghq posh-git
      - pwsh -File ./install-deps.ps1
    silent: true
  generate-completion:
    cmds:
      - pwsh -File ./completion.generate.ps1
  install:
    deps:
      - install-deps
      - generate-completion
    cmds:
      - pnpm install
    silent: true
  update:
    deps:
      - generate-completion
    cmds:
      - pnpm update
  clean:
    cmds:
      - rm -rf bins/
      - rm -rf init.generated.d/
      - rm -rf node_modules/
